# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6.7", "3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pwd
        ls
        python -m pip install --upgrade pip
        python -m pip install -r cascade/tests/requirements.txt
        python -m pip install ".[all]"

    - name: Lint with flake8
      run: |
        # stop the build if any syntax errors
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
        # lint
        flake8 --statistics --exit-zero

    - name: Test
      run: |
        pwd
        ls
        python --version
        cd ./cascade/tests
        pytest --cov=cascade .
    - name: Test utils
      run: |
        pwd
        ls
        cd ./cascade/utils/tests
        pytest
